apiVersion: v1
kind: PersistentVolume
metadata:
  name: opt-local-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  hostPath:
    path: /opt/sftpdata
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2.raghavocp46.cp.fyre.ibm.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status: {}