apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual #your custom storage class name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi